### ISSUE TITLE
Response Curve error when creating model report

### ISSUE THREAD

**Issue by DevinALyons** [ConsBiol-unibern/SDMtune#12]
Over the past few days I've had an error pop up occasionally. Never seen it before, despite using the package over the past 4 or 5 months.

The model report function starts working, but then I get:
-- Model Report - method: Maxnet ------------------------------- HemiRisk2019 --
v Saving files...
v Plotting ROC curve...
v Computing thresholds...
v Plotting marginal response curves...
- Plotting univariate response curves...Quitting from lines 84-99 (modelReport.Rmd) 
Error in sqrt(np) : non-numeric argument to mathematical function

I've noticed this pop up when response_curves=TRUE, obviously, and fc="lp" in the model. I just had it happen again twice. When I changed to fc="lph", for the same data, everything is  fine. I'm pretty sure fc="lp" models have worked in the past though. I pretty much always use cloglog, if that might matter.

**Comment by sgvignali** [comment]
I think this is due to the package maxnet that generates the error when trained with only one variable and using the lp feature combination. In this case I cannot do anything.

The only thing I can do is to provide an argument to the modelReport function to skip the univariate response curves so that you can still plot the marginal one and have the rest of the report

**Comment by DevinALyons** [comment]
OK. Strange that it is a problem for "lp" but not for more complex models that still have product features.......
